Enumerables to develop
DickensJuma/Enumerables pull request #1
Opened 2020-06-01 10:09 UTC by DickensJuma

**Creating Enumerable**

- Created methods
- Lintered errors
- Used git-flow

2020-06-01 13:25 UTC, mikenath223 requested changes
### Hi @DickensJuma  👋

You seem to have done your best on this, kudos. 👌
However, it seems you mostly have an issue with my_any? the method, but let's start with the my_all method. 👍

- [ ] my_all is expected to return the right value when a Ruby class is passed as an argument, but yours returns true rather than false in [this case](https://user-images.githubusercontent.com/33323077/83412723-8a026200-a412-11ea-9e03-3e85e587bedb.png).

- [ ] my_any? throws an error when any value is passed to it, you didn't define a my_any method, you need to add a `my_any?` method as it is part of the enumerable to be built as [described here](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods). [Screenshot]👇
![ice_screenshot_20200601-142345](https://user-images.githubusercontent.com/33323077/83413387-a9e65580-a413-11ea-94dc-dbf914932e09.png)


Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-06-01 18:40 UTC, kobiyoyo requested changes
## Hi @DickensJuma       ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Lets activate stickler for this project. 
- [ ] Lets include `my_any` method in your code
- [ ] `my_any?`:
- returns true if the block ever returns a value other than false or nil
`block = proc { |num| num <= 3 }`
`p [12,12,13,1,4].my_any?(&block)` should return `true`

- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
`p [12,3,34].my_any?(Integer)` should return `true`
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
`p ['ghetto','wild'].my_any?(/z/)` should return `false`
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p ['cat',2,32,].my_any?('cat')` should return `true`

- [ ] `my_all?`  
- when a class is passed as an argument returns true if all the collection is a member of such class
`p [1,1,1].my_all?(Integer)` should return `true`
-  when a Regex is passed as an argument returns true if all the collection matches the Regex
`p ['d','d'].my_all?(/d/)` should return `true`
- when a pattern other than Regex or a Class is given returns true if all the collection matches the pattern
`p [3,3,3,3].my_all?(3)` should return `true`

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-02 00:53 UTC, lekegitrepo commented
#### Hi @DickensJuma :clap: :clap:
#### Good job so far, you have fixed most of the required changes but you still need to handle this test cases as mention in the previous review:

**_1. [12,3,34].my_any?(Integer) should return true._**

**_2. Enable the stickler for this project._**

### _Reviewed by Temitayo Adeleke._

2020-06-02 00:54 UTC, lekegitrepo requested changes
#### Status: Request changes

2020-06-02 08:21 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for the improvements done so far.
However, there are still changes to do

1. Fix the stickler's errors

2. Read the comment below.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-06-02 08:21 UTC, maelfosso commented on main.rb
> +  end
```ruby
2.6.3 :007 > array
 => [6, 4, 1, 2, 0, 7, 8, 4, 5, 2, 5, 6, 7, 5, 7, 4, 0, 6, 4, 3, 1, 5, 1, 4, 1, 5, 3, 4, 3, 7, 0, 5, 4, 3, 2, 3, 8, 7, 5, 1, 4, 6, 3, 6, 2, 2, 5, 2, 1, 1, 0, 1, 8, 5, 6, 8, 4, 2, 1, 8, 6, 8, 7, 2, 2, 2, 7, 8, 8, 6, 0, 1, 4, 2, 3, 1, 8, 4, 3, 1, 7, 3, 1, 3, 4, 8, 2, 3, 1, 5, 4, 3, 3, 4, 2, 6, 3, 7, 5, 3] 
2.6.3 :008 > array.all?(Integer)
 => true 
2.6.3 :009 > array.my_all?(Integer)
 => false 
2.6.3 :010 > 
```

2020-06-02 08:21 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.3 :012 > array
 => [6, 4, 1, 2, 0, 7, 8, 4, 5, 2, 5, 6, 7, 5, 7, 4, 0, 6, 4, 3, 1, 5, 1, 4, 1, 5, 3, 4, 3, 7, 0, 5, 4, 3, 2, 3, 8, 7, 5, 1, 4, 6, 3, 6, 2, 2, 5, 2, 1, 1, 0, 1, 8, 5, 6, 8, 4, 2, 1, 8, 6, 8, 7, 2, 2, 2, 7, 8, 8, 6, 0, 1, 4, 2, 3, 1, 8, 4, 3, 1, 7, 3, 1, 3, 4, 8, 2, 3, 1, 5, 4, 3, 3, 4, 2, 6, 3, 7, 5, 3] 
2.6.3 :013 > array.all?(3)
 => false 
2.6.3 :014 > array.my_all?(3)
 => true 
2.6.3 :015 > 
```

2020-06-02 08:21 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.3 :017 > true_array = [nil, false, true, []]
 => [nil, false, true, []] 
2.6.3 :018 > true_array.any?
 => true 
2.6.3 :019 > true_array.my_any?
Traceback (most recent call last):
        9: from /usr/share/rvm/rubies/ruby-2.6.3/bin/irb:23:in `<main>'
        8: from /usr/share/rvm/rubies/ruby-2.6.3/bin/irb:23:in `load'
        7: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        6: from (irb):19
        5: from main.rb:46:in `my_any?'
        4: from main.rb:7:in `my_each'
        3: from main.rb:7:in `upto'
        2: from main.rb:8:in `block in my_each'
        1: from main.rb:55:in `block in my_any?'
NameError (undefined local variable or method `value' for [nil, false, true, []]:Array)
Did you mean?  values_at
2.6.3 :020 > 
```

2020-06-02 08:21 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.3 :023 > array
 => [6, 4, 1, 2, 0, 7, 8, 4, 5, 2, 5, 6, 7, 5, 7, 4, 0, 6, 4, 3, 1, 5, 1, 4, 1, 5, 3, 4, 3, 7, 0, 5, 4, 3, 2, 3, 8, 7, 5, 1, 4, 6, 3, 6, 2, 2, 5, 2, 1, 1, 0, 1, 8, 5, 6, 8, 4, 2, 1, 8, 6, 8, 7, 2, 2, 2, 7, 8, 8, 6, 0, 1, 4, 2, 3, 1, 8, 4, 3, 1, 7, 3, 1, 3, 4, 8, 2, 3, 1, 5, 4, 3, 3, 4, 2, 6, 3, 7, 5, 3] 
2.6.3 :024 > array.any?(Integer)
 => true 
2.6.3 :025 > array.my_any?(Integer)
 => false 
2.6.3 :026 > 
```

2020-06-02 16:22 UTC, Dandush03 reviewed
# Status: 🔴 Required Changes 🔴 

## Hey guys! 👋  you're almost there.
#### please check out my comments below and fix does issue.

# Happy Coding 💻 

Daniel Laloush

2020-06-02 16:22 UTC, Dandush03 commented on main.rb
> +  end
### #my_all
enumerables my_all? when no block or argument is given returns true when none of the collection members are false or nil
``` ruby
irb>arr = { [1, false, 'hello', [] }
irb>arr.my_all?
  => true
```
> expected to be false
------
Your code isn't receiving arguments when given, check [API DOCK](https://apidock.com/ruby/Enumerable/all%3F)
``` ruby
irb>arr = Array.new(100) { rand(0...9) }
irb>arr.my_all(Integer)?
  => wrong number of arguments (given 1, expected 0)
```
> expected to be true

2020-06-02 16:22 UTC, Dandush03 commented on main.rb
> +  end
### #my_any 
enumerable my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
``` ruby
irb>arr = [false, false]
irb>arr.my_any?
  => true
```
> expected to be false
------
enumerable my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
``` ruby
irb>arr = %w[testdoor roadtest test]
irb>arr.my_any?(Integer)
  => true
```
> expected to be false
------
enumerable my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
``` ruby
irb>arr = %w[testdoor roadtest test]
irb>arr.my_any?(/z/)
  => true
```
> expected to be false
------
enumerable my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
``` ruby
irb>arr = %w[testdoor roadtest test]
irb>arr.my_any?('tim')
  => true
```
> expected to be false

2020-06-06 19:59 UTC, davitomix commented
## Hi @DickensJuma .
### Very good job so far.

However, there are some issues with the my_all and my_any methods that need to be implemented fixed, please checkout below.  👨‍💻  ⬇️ 

****
**Please make the changes required and submit for re-review once you are ready!** 
****
## Status: Changes required. ♻️  
****


**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

2020-06-06 20:05 UTC, davitomix commented on main.rb
> +  end
enumerable my_all? returns true when none of the collection members are false or nil.
```
=> arr = [0, false, 7, 4, 5, 8, 9, 1, 9, 0]
=> arr.all?
=> false
=> arr.my_all?
=> true
```

Expected to be false.

2020-06-06 20:11 UTC, davitomix commented on main.rb
> +
enumerable my_any? return true if at least one of the collection members is not false or nil when no block is given.

=> arr = [1, false, 'hello', 4, 20]
=> arr.any?(Numeric)
=> true
=> arr.my_any?(Numeric)
=> false
Expected to be true.

2020-06-10 12:11 UTC, Torres-ssf approved these changes
### Project Approved :tada: 
Hi there @DickensJuma 
Great work on this project :+1: :clap: 
I'm approving the PR but there is something that I need to point out.

**Some of your methods are missing specific behaviors from the original methods. Since changes related to these behaviors were not requested in previous reviews, I'm approving the PR and leaving them as optional.**

**OPTIONAL**
- [ ] The multiply_els method was not implemented.

- [ ]  Check the comments below.

Good luck with your next project
Happy coding :computer:

2020-06-10 12:11 UTC, Torres-ssf commented on main.rb
> +  end
**OPTIONAL**
- [ ] when a block is given when self is a range returns the range itself after calling the given block once for each element in self. Your method is returning an array even when you call the method from a range.

`(1..5).my_each { |x| p x }` should print all numbers from 1 to 5 and return the range itself afterward. 

Print of the original method:
![Screenshot from 2020-06-10 08-50-36](https://user-images.githubusercontent.com/30977845/84264389-7aaca400-aaf7-11ea-8b1a-8ac7d5f782c7.png)

2020-06-10 12:11 UTC, Torres-ssf commented on main.rb
> +  end
**OPTIONAL**
- [ ] my_each_with_index, when a block is given when self is a range, returns the range itself after calling the given block once for each element in self. Your method is returning an array even when you call the method from a range.

`(1..5).my_each_with_index { |x, index| p index }` should print all indexes from 0 to 4 and return the range itself afterward. 

Print of the original method:
![Screenshot from 2020-06-10 08-54-25](https://user-images.githubusercontent.com/30977845/84264704-045c7180-aaf8-11ea-9850-d8abf1b694c6.png)

2020-06-10 12:11 UTC, Torres-ssf commented on main.rb
> +  end
**OPTIONAL**

- [ ] my_count returns the number of items in enum through enumeration. This error is happening because your method it's dealing with ranges.

`(1..5)my_count` should return 5

Print of the original method:

![Screenshot from 2020-06-10 08-58-03](https://user-images.githubusercontent.com/30977845/84265014-851b6d80-aaf8-11ea-97ca-12a28491b3ee.png)

2020-06-10 12:11 UTC, Torres-ssf commented on main.rb
> +end
**OPTIONAL**

- [ ] my_inject raises a "LocalJumpError" when no block or argument is given.

`[1,2,3,4,5].my_inject` should raise a LocalJumpError

Print from the original method:

![Screenshot from 2020-06-10 09-00-17](https://user-images.githubusercontent.com/30977845/84265183-d166ad80-aaf8-11ea-8c3b-10206a608bec.png)

2020-06-12 12:16 UTC, merged